### ISSUE TITLE
Not able to pust the presentation

### ISSUE THREAD

**Issue by nsrivastava645** [gaurav-gogia/KameKazi#13]
I tried pushing as per your specified readme file but was unable to push it, it says acess denied.

**Comment by gaurav-gogia** [comment]
I see. Can you please state your steps while trying to push data? From this information, I can only derive that you might have missed forking the repository or maybe you cloned this repo instead of your own fork. If that is the case then following the contribution guidelines can help.

Though feel free to ask any questions if you get stuck or provide any suggestions if you have a better idea in mind. ^.^

Thanks for your interest, I look forward to your PR.

**Comment by nsrivastava645** [comment]
Ah I've not ever done anything on Github so I guess that forking thing is
the main issue.I'll try doing that again by forking it.
Thanks for the response.

Regards
Neeraj srivastava

**Comment by gaurav-gogia** [comment]
Merged. Thanks!

**Comment by nsrivastava645** [comment]
You're welcome, I wanted to ask can you connect me on LinkedIn?


Here's my LinkedIn profile link:

https://www.linkedin.com/in/neeraj-srivastava-b91a84155

**Comment by gaurav-gogia** [comment]
Connection request sent :)
